# Generated by Django 4.2.11 on 2025-11-10 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_projects_portfolio_about_portfolio_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.portfolio'),
        ),
        migrations.DeleteModel(
            name='ProjectInPortfolio',
        ),
    ]
