# Generated by Django 4.2.11 on 2025-11-10 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_projects_portfolio_delete_projectinportfolio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.RemoveField(
            model_name='student',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.student'),
        ),
    ]
