# Generated by Django 4.2.11 on 2025-11-17 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_rename_projects_project_remove_student_portfolio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='student',
        ),
        migrations.AddField(
            model_name='student',
            name='Portfolio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_app.portfolio'),
        ),
    ]
