# Generated by Django 5.2.7 on 2025-11-28 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_remove_portfolio_student_student_portfolio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Portfolio',
            new_name='portfolio',
        ),
    ]
